#!/bin/sh
#
# run a program directly on the virtual terminal

[ $# -lt 1 ] && echo "program to run missing" && exit 1

if ! $SCROLLBACK false;
then
	exec "${@}"
	exit 1
fi

SCRIPT=$HOME/.scrollback.$SCROLLBACKNO

cat /dev/null			>  $SCRIPT
env | sed 's,^,export ,'	>> $SCRIPT
echo "cd $(pwd)"		>> $SCRIPT
echo "$1"			>> $SCRIPT

echo -en '\033[0v'

