#!/bin/sh
#
# run a program directly on the virtual terminal

[ $# -lt 1 ] && echo "program to run missing" && exit 1

if ! $SCROLLBACK false;
then
	exec "${@}"
	exit 1
fi

echo "$1" > $HOME/.scrollback.$SCROLLBACKNO
echo -en '\033[0v'

